version: '3.7'

services:
    web:
        build:
            context: lde_config/lde/nginx
        volumes:
            - .:/srv/site/demos:z
            - ./lde_config/nginx_site.conf:/etc/nginx/conf.d/default.conf:z,delegated
        networks:
            - net
            - lde_net
        labels:
            - "learnosity.app_name=site-demos"
            - "learnosity.app_root=${PWD}"
            - "traefik.frontend.rule=Host:demos.dev.learnosity.com"
            - "traefik.port=80"
            - "traefik.docker.network=lde_net"
            - "traefik.frontend.entryPoints=https"
            - "traefik.backend.loadbalancer.swarm=true"
            - "traefik.backend.loadbalancer.method=drr"
            - "traefik.enable=true"
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: lde_config/lde/php-fpm
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
        volumes:
            - .:/srv/site/demos:z,delegated
        networks:
            - net
            - lde_internal
        dns:
            - 192.168.199.3

networks:
    net:
    lde_net:
        external: true
    lde_internal:
        external: true
